#!/bin/bash
if [ -z "$1" ]; then
	echo "No Domain specified"
	echo "Usage: uber-del-subdomain <domain.tld>"
else
	uberspace-del-domain -w -d $1
	echo "DELETE Webserver Folder @ /var/www/virtual/$USER/$1"
	rm -rf /var/www/virtual/$USER/$1
	echo "[OK]"
fi
