#!/bin/bash
letsencrypt-renewer --config-dir ~/.config/letsencrypt --logs-dir ~/.config/letsencrypt/logs --work
for i in $(ls ~/.config/letsencrypt/live/) do
  uberspace-prepare-certificate -k ~/.config/letsencrypt/live/$NAME/privkey.pem -c ~/.config/letsencrypt/$NAME/cert.pem
done
